# Generated by Django 5.1 on 2024-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
