# Generated by Django 5.1 on 2024-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_customuser_resume_customuser_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='resume',
            new_name='certifications',
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
