# Generated by Django 5.1 on 2024-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
